---
- name: ensure packages are installed
  package:
    name: "{{ item }}"
  with_items:
    - pulseaudio
    - pulseaudio-utils

- name: ensure packages for avahi is installed
  package:
    name: "{{ item }}"
  with_items:
    - pulseaudio-module-zeroconf
    - avahi
  when: pulseaudio_avahi

- name: ensure user is in group audio
  user:
    name: pulse
    append: yes
    groups: audio

- name: ensure autospawn is disabled
  lineinfile:
    dest: /etc/pulse/client.conf
    regexp: '^.*autospawn =.*'
    line: autospawn = no

- name: ensure network module is loaded
  lineinfile:
    dest: /etc/pulse/system.pa
    line: load-module module-native-protocol-tcp auth-anonymous=1
  when: pulseaudio_network or pulseaudio_avahi
  notify:
    - restart pulseaudio

- name: ensure network module is not loaded
  lineinfile:
    dest: /etc/pulse/system.pa
    state: absent
    regexp: '^load-module module-native-protocol-tcp'
  when: not pulseaudio_network and not pulseaudio_avahi
  notify:
    - restart pulseaudio

- name: ensure zeroconf module is loaded
  lineinfile:
    dest: /etc/pulse/system.pa
    line: load-module module-zeroconf-publish
  when: pulseaudio_avahi
  notify:
    - restart pulseaudio

- name: ensure zeroconf module is not loaded
  lineinfile:
    dest: /etc/pulse/system.pa
    state: absent
    regexp: '^load-module module-zeroconf-publish'
  when: not pulseaudio_avahi
  notify:
    - restart pulseaudio

- name: ensure service is installed
  template:
    src: pulseaudio.service.j2
    dest: /etc/systemd/system/pulseaudio.service
    owner: root
    group: root
    mode: 0644

- name: ensure service is enabled
  service:
    name: pulseaudio
    enabled: yes
    state: started

- name: ensure avahi socket is enabled or disabled
  service:
    name: avahi-daemon.socket
    enabled: "{{ pulseaudio_avahi }}"

- name: ensure pulseaudio port is open or closed in firewall
  firewalld:
    service: pulseaudio
    zone: "{{ item }}"
    permanent: true
    state: "{% if pulseaudio_network or pulseaudio_avahi %}enabled{% else %}disabled{% endif %}"
  with_items: "{{ pulseaudio_firewall_zones }}"

- name: ensure avahi port is open or closed in firewall
  firewalld:
    service: mdns
    zone: "{{ item }}"
    permanent: true
    state: "{% if pulseaudio_avahi %}enabled{% else %}disabled{% endif %}"
  with_items: "{{ pulseaudio_firewall_zones }}"
